NAMA : Rida Tsaniya Putri Hamdani

NIM : 2404010005

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pandas untuk mengolah tabel, numpy untuk operasi angka/NaN, matplotlib untuk visualisasi (belum dipakai di sini).

In [2]:
url = "https://raw.githubusercontent.com/Rida06-sud/zomato-data-cleaning/main/Zomato%20Restaurant%20Dataset.csv"
df = pd.read_csv(url, sep=",", dtype=str, keep_default_na=False)

sep=":" baca CSV dengan pemisah ;. Semua kolom dibaca sebagai teks (dtype=str) supaya tidak ada data yang berubah otomatis, dan sel kosong tetap "" (tidak langsung jadi NaN). Tujuannya agar bisa diperiksa manual dulu.

In [3]:
print(df.shape)
print(df.columns.tolist())

(9551, 21)
['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']

untuk melihat jumlah baris dan kolom

In [4]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.58445,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

untuk menunjukkan 5 baris pertama

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   object
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   object
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   object
 8   Latitude              9551 non-null   object
 9   Cuisines              9551 non-null   object
 10  Average Cost for two  9551 non-null   object
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   object
 17  Aggregate rating      9551 non-null   object
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   object
dtypes: object(21)
memory usage: 1.5+ MB

untuk memberikan informasi terkait tipe data dan jumlah nilai non-null per kolom

In [6]:
(df == "").sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

berguna untuk menghitung sel kosong per kolomnya

In [7]:
df.duplicated().sum()

np.int64(0)

untuk mengecek apakah ada baris yang duplikat

In [8]:
df["Switch to order menu"].value_counts()

Switch to order menu
No    9551
Name: count, dtype: int64

Syntax ini menghitung jumlah tiap nilai unik di kolom Switch to order menu. Hasilnya hampir semuanya "No" (9545), sisanya berupa nilai nyasar seperti kosong, angka, atau teks ("2", "Average", "3.8"), yang menunjukkan ada baris bergeser dan kolom ini tidak berguna, sehingga nanti dibuang.

In [9]:
df["Currency"].value_counts()

Currency
Indian Rupees(Rs.)        8652
Dollar($)                  482
Pounds(��)                  80
Brazilian Real(R$)          60
Rand(R)                     60
Emirati Diram(AED)          60
NewZealand($)               40
Turkish Lira(TL)            34
Botswana Pula(P)            22
Indonesian Rupiah(IDR)      21
Qatari Rial(QR)             20
Sri Lankan Rupee(LKR)       20
Name: count, dtype: int64

In [10]:
df[~df["Restaurant ID"].str.fullmatch(r"\d+")]

Empty DataFrame
Columns: [Restaurant ID, Restaurant Name, Country Code, City, Address, Locality, Locality Verbose, Longitude, Latitude, Cuisines, Average Cost for two, Currency, Has Table booking, Has Online delivery, Is delivering now, Switch to order menu, Price range, Aggregate rating, Rating color, Rating text, Votes]
Index: []

[0 rows x 21 columns]

untuk mengecek apakah restaurant id hanya berisi angka, kalau tidak berarti baris itu akan bergeser/rusak

In [11]:
print("Sebelum:", df.shape)

# baris ekor: ID bukan angka | baris kepala: Locality kosong
baris_rusak = ~df["Restaurant ID"].str.fullmatch(r"\d+") | (df["Locality"] == "")
print("Baris rusak:", baris_rusak.sum())

df = df[~baris_rusak].reset_index(drop=True)
print("Sesudah:", df.shape)

Sebelum: (9551, 21)
Baris rusak: 0
Sesudah: (9551, 21)

Syntax ini membuang baris data yang rusak, yaitu baris yang Restaurant ID-nya bukan angka atau Locality-nya kosong, lalu merapikan ulang index, sehingga data berkurang dari 9557 menjadi 9545 baris.

In [12]:
print("Nama dengan karakter rusak:", df["Restaurant Name"].str.contains("\ufffd").sum())
print(df.loc[df["Restaurant Name"].str.contains("\ufffd"), "Restaurant Name"].head())

Nama dengan karakter rusak: 103
23    Caf�� Daniel Briand
26         Pizza �� Bessa
30         Sandubas Caf��
36                 Tayp��
38                Manzu��
Name: Restaurant Name, dtype: object

Syntax ini mengecek berapa banyak nama restoran yang mengandung karakter rusak (�) akibat masalah encoding, lalu menampilkan contoh lima nama pertamanya (hasilnya 103 nama, misalnya "Caf�� Daniel Briand").

In [13]:
# hapus spasi di awal/akhir di semua kolom
for c in df.columns:
    df[c] = df[c].str.strip()

# hapus karakter rusak di kolom teks
for c in ["Restaurant Name", "City", "Address", "Locality", "Cuisines"]:
    df[c] = df[c].str.replace("\ufffd", "", regex=False)

In [14]:
sorted(df["City"].unique())[:15]

['Abu Dhabi',
 'Agra',
 'Ahmedabad',
 'Albany',
 'Allahabad',
 'Amritsar',
 'Ankara',
 'Armidale',
 'Athens',
 'Auckland',
 'Augusta',
 'Aurangabad',
 'Balingup',
 'Bandung',
 'Bangalore']

Syntax ini menampilkan 15 nama kota pertama yang unik dari kolom City, diurutkan sesuai abjad (unique() mengambil nilai tanpa duplikat, sorted() mengurutkan, [:15] memotong 15 pertama), untuk memeriksa apakah ada nama kota yang masih aneh atau rusak.

In [15]:
df[df["Country Code"].isin(["30", "208"])]["City"].unique()

array(['Bras_lia', 'Rio de Janeiro', 'So Paulo', 'Ankara', 'stanbul'],
      dtype=object)

In [16]:
df["City"] = df["City"].replace({
    "Bras_lia": "Brasília",
    "So Paulo": "São Paulo",
    "stanbul": "İstanbul"
})

In [17]:
df[df["Country Code"].isin(["30", "208"])]["City"].unique()

array(['Brasília', 'Rio de Janeiro', 'São Paulo', 'Ankara', 'İstanbul'],
      dtype=object)

In [18]:
df = df.replace("", np.nan)
df.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

Syntax ini mengubah semua sel berisi string kosong ("") menjadi NaN, yaitu penanda resmi pandas untuk data hilang, lalu df.isna().sum() menghitung jumlah data hilang di tiap kolom (hasilnya hanya Cuisines yang masih punya 9 data kosong).

In [19]:
for c in ["Has Table booking", "Has Online delivery", "Is delivering now"]:
    df[c] = df[c].map({"Yes": 1, "No": 0})

Syntax ini mengubah tiga kolom berisi "Yes"/"No"menjadi angka 1 dan 0 lewat perulangan for dan .map(), supaya datanya berbentuk numerik dan lebih mudah dianalisis.

In [20]:
angka = ["Restaurant ID", "Country Code", "Average Cost for two",
         "Price range", "Aggregate rating", "Votes"]
for c in angka:
    df[c] = pd.to_numeric(df[c], errors="coerce")

Syntax ini mengubah enam kolom yang seharusnya berisi angka (Restaurant ID, Country Code, Average Cost for two, Price range, Aggregate rating, Votes) dari tipe teks menjadi tipe numerik memakai pd.to_numeric(), dan errors="coerce" membuat nilai yang gagal diubah otomatis menjadi NaN, bukan menyebabkan error.

In [21]:
negara = {1: "India", 14: "Australia", 30: "Brazil", 37: "Canada", 94: "Indonesia",
          148: "New Zealand", 162: "Philippines", 166: "Qatar", 184: "Singapore",
          189: "South Africa", 191: "Sri Lanka", 208: "Turkey", 214: "UAE",
          215: "UK", 216: "USA"}

mata_uang = {1: "INR", 14: "AUD", 30: "BRL", 37: "CAD", 94: "IDR",
             148: "NZD", 162: "PHP", 166: "QAR", 184: "SGD",
             189: "ZAR", 191: "LKR", 208: "TRY", 214: "AED",
             215: "GBP", 216: "USD"}

df["Country"] = df["Country Code"].map(negara)
df["Currency Code"] = df["Country Code"].map(mata_uang)
df = df.drop(columns=["Currency"])

Syntax ini membuat dua kamus (negara dan mata_uang) yang memetakan kode negara ke nama negara dan kode mata uang (misalnya 94 menjadi "Indonesia" dan "IDR"), lalu .map() memakainya untuk membuat kolom baru Country dan Currency Code dari Country Code, dan terakhir kolom Currency yang lama (teksnya berantakan) dibuang dengan drop().

In [22]:
df.dtypes

Restaurant ID             int64
Restaurant Name          object
Country Code              int64
City                     object
Address                  object
Locality                 object
Locality Verbose         object
Longitude                object
Latitude                 object
Cuisines                 object
Average Cost for two      int64
Has Table booking         int64
Has Online delivery       int64
Is delivering now         int64
Switch to order menu     object
Price range               int64
Aggregate rating        float64
Rating color             object
Rating text              object
Votes                     int64
Country                  object
Currency Code            object
dtype: object

In [23]:
df[["Country", "Currency Code"]].value_counts()
df["Country"].isna().sum()

np.int64(0)

In [24]:
print("Rating = 0        :", (df["Aggregate rating"] == 0).sum())
print("Rating 'Not rated':", (df["Rating text"] == "Not rated").sum())
print("Biaya = 0         :", (df["Average Cost for two"] == 0).sum())

Rating = 0        : 2148
Rating 'Not rated': 2148
Biaya = 0         : 18

In [25]:
# kolom penanda: restoran sudah dinilai atau belum
df["Is Rated"] = (df["Rating text"] != "Not rated").astype(int)

# rating 0 -> NaN (karena sebenarnya belum dinilai)
df.loc[df["Is Rated"] == 0, "Aggregate rating"] = np.nan

# biaya 0 tidak masuk akal -> NaN
df.loc[df["Average Cost for two"] == 0, "Average Cost for two"] = np.nan

In [26]:
df["Aggregate rating"].describe()

count    7403.000000
mean        3.440024
std         0.552195
min         1.800000
25%         3.000000
50%         3.400000
75%         3.800000
max         4.900000
Name: Aggregate rating, dtype: float64

In [27]:
df["Is Rated"].value_counts()

Is Rated
1    7403
0    2148
Name: count, dtype: int64

Syntax ini menghitung jumlah tiap nilai di kolom Is Rated, yaitu berapa restoran yang sudah dinilai (1 = 7399) dan yang belum dinilai (0 = 2146).

In [28]:
df[["Restaurant Name", "Country Code", "Longitude", "Latitude"]].head(8)

          Restaurant Name  Country Code    Longitude     Latitude
0        Le Petit Souffle           162   121.027535    14.565443
1        Izakaya Kikufuji           162   121.014101    14.553708
2  Heat - Edsa Shangri-La           162   121.056831    14.581404
3                    Ooma           162   121.056475    14.585318
4             Sambo Kojin           162   121.057508     14.58445
5            Din Tai Fung           162   121.056314    14.583764
6              Buffet 101           162  120.9796667  14.53133333
7                 Vikings           162  120.9793333        14.54

In [29]:
pd.to_numeric(df["Longitude"], errors="coerce").isna().sum()

np.int64(0)

In [30]:
def fix_coord(x, lo, hi):
    if pd.isna(x):
        return np.nan
    sign = -1 if x.startswith("-") else 1
    digits = x.replace("-", "").replace(".", "")
    if int(digits) == 0:
        return np.nan
    for k in (1, 2, 3):
        if len(digits) > k:
            val = sign * float(digits[:k] + "." + digits[k:])
            if lo <= val <= hi:
                return val
    return np.nan

batas = {
    1:   ((68, 98),    (6, 37)),
    14:  ((112, 154),  (-44, -10)),
    30:  ((-75, -34),  (-34, -10)),
    37:  ((-141, -52), (41, 84)),
    94:  ((95, 141),   (-11, 6)),
    148: ((166, 179),  (-47, -34)),
    162: ((116, 127),  (4, 21)),
    166: ((50, 52),    (24, 27)),
    184: ((103, 105),  (1, 2)),
    189: ((16, 33),    (-35, -22)),
    191: ((79, 82),    (5, 10)),
    208: ((26, 45),    (36, 42)),
    214: ((51, 57),    (22, 26.5)),
    215: ((-8, 2),     (49, 61)),
    216: ((-125, -66), (24, 50)),
}

df["Longitude"] = df.apply(lambda r: fix_coord(r["Longitude"], *batas[r["Country Code"]][0]), axis=1)
df["Latitude"]  = df.apply(lambda r: fix_coord(r["Latitude"],  *batas[r["Country Code"]][1]), axis=1)

Fungsi fix_coord(x, lo, hi):
Simpan tanda negatif, lalu ambil semua digit tanpa titik/minus.
Kalau semuanya nol, kembalikan NaN.
Coba sisipkan titik desimal setelah digit ke-1, ke-2, atau ke-3.
Terima hasil pertama yang masuk di rentang lo–hi (batas wajar koordinat negara tersebut), kalau tidak ada yang cocok jadi NaN.
Dictionary batas: rentang longitude/latitude yang valid per negara, jadi posisi titik desimal bisa ditebak dengan benar.
df.apply(lambda r: ..., axis=1): terapkan fungsi ke tiap baris sesuai negaranya.

In [31]:
df[["Restaurant Name", "Country", "Longitude", "Latitude"]].head(8)

          Restaurant Name      Country   Longitude   Latitude
0        Le Petit Souffle  Philippines  121.027535  14.565443
1        Izakaya Kikufuji  Philippines  121.014101  14.553708
2  Heat - Edsa Shangri-La  Philippines  121.056831  14.581404
3                    Ooma  Philippines  121.056475  14.585318
4             Sambo Kojin  Philippines  121.057508  14.584450
5            Din Tai Fung  Philippines  121.056314  14.583764
6              Buffet 101  Philippines  120.979667  14.531333
7                 Vikings  Philippines  120.979333  14.540000

In [32]:
df["Longitude"].isna().sum()

np.int64(519)

In [33]:
df.groupby("Country")[["Longitude", "Latitude"]].agg(["min", "max"]).round(2)

             Longitude         Latitude
                   min     max      min    max
Country
Australia       115.98  153.59   -38.63 -16.75
Brazil          -48.02  -43.16   -23.62 -15.72
Canada         -110.77  -79.38    42.40  52.01
India            72.50   91.81     9.96  31.66
Indonesia       106.65  107.61    -6.89  -6.10
New Zealand     174.64  174.83   -41.33 -36.84
Philippines     120.95  121.08    14.10  14.65
Qatar            51.35   51.55    25.22  25.35
Singapore       103.81  103.86     1.28   1.33
South Africa     18.38   28.33   -33.98 -25.76
Sri Lanka        79.84   79.90     6.85   6.93
Turkey           28.98   32.87    39.88  41.10
UAE              54.36   55.46    24.33  25.36
UK               -3.21   -0.08    51.49  55.98
USA            -124.18  -74.65    27.77  46.37

memvalidasi bahwa min/max koordinat tiap negara masuk akal. setelah perbaikan hanya ada 519 data longitude yang kosong

In [34]:
df["Longitude"].isna().sum()

np.int64(519)

In [35]:
pd.crosstab(df["Rating text"], df["Rating color"])

Rating color  Dark Green  Green  Orange  Red  White  Yellow
Rating text
Average                0      0    3737    0      0       0
Excellent            301      0       0    0      0       0
Good                   0      0       0    0      0    2100
Not rated              0      0       0    0   2148       0
Poor                   0      0       0  186      0       0
Very Good              0   1079       0    0      0       0

In [36]:
df = df.drop(columns=["Switch to order menu", "Rating color", "Locality Verbose"])
df.shape

(9551, 20)

bertujuan untuk membuang kolom yang tidak berguna sehingga hanya tersisa 20 kolom

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Longitude             9032 non-null   float64
 7   Latitude              9030 non-null   float64
 8   Cuisines              9542 non-null   object
 9   Average Cost for two  9533 non-null   float64
 10  Has Table booking     9551 non-null   int64
 11  Has Online delivery   9551 non-null   int64
 12  Is delivering now     9551 non-null   int64
 13  Price range           9551 non-null   int64
 14  Aggregate rating      7403 non-null   float64
 15  Rating text           9551 non-null   object
 16  Votes                 9551 non-null   int64
 17  Country               9551 non-null   object
 18  Currency Code         9551 non-null   object
 19  Is Rated              9551 non-null   int64
dtypes: float64(4), int64(8), object(8)
memory usage: 1.5+ MB

untuk mengecek apakah terdapat perubahan setelah terjadi pembuanga kolom dari syntax diatas

In [38]:
df.isna().sum()[df.isna().sum() > 0]

Longitude                519
Latitude                 521
Cuisines                   9
Average Cost for two      18
Aggregate rating        2148
dtype: int64

In [39]:
# isi data kosong
df["Cuisines"] = df["Cuisines"].fillna("Unknown")

# biaya: median per Country + Price range, lalu per Country
df["Average Cost for two"] = df.groupby(["Country", "Price range"])["Average Cost for two"] \
                               .transform(lambda s: s.fillna(s.median()))
df["Average Cost for two"] = df.groupby("Country")["Average Cost for two"] \
                               .transform(lambda s: s.fillna(s.median()))

# koordinat: median per City, lalu per Country
for c in ["Longitude", "Latitude"]:
    df[c] = df.groupby("City")[c].transform(lambda s: s.fillna(s.median()))
    df[c] = df.groupby("Country")[c].transform(lambda s: s.fillna(s.median()))

# cek sisa kosong (harusnya cuma Aggregate rating)
df.isna().sum()[df.isna().sum() > 0]

Aggregate rating    2148
dtype: int64

pengecekan akhir tipe data dan sisa missing value

In [40]:
df.to_csv("Zomato_cleaned.csv", index=False)
df.to_excel("Zomato_cleaned.xlsx", index=False)

Untuk menyimpan hasil dari procesing ke csv

In [41]:
cek = pd.read_csv("Zomato_cleaned.csv")
print(cek.shape)

(9551, 20)

untuk memastikan file yang disimpan ukuranya tetap sama